### ISSUE TITLE
internal exception: java.lang.nullpointerexception error when entering a singleplayer world

### ISSUE THREAD

**Issue by ThisIsAVeryOriginalName** [edoren/SkinChanger#28]
1.19.2
This appears to be a partial Incompatibility with the Vampirism mod. (Vampirism - Become a vampire!)
I'm not sure if it is just Vampirism, or any mod that changes the player character.

I attempted to join my single player world and was met with "internal exception: java.lang.nullpointerexception"
By disabling the mod and re-entering the world I saw I was in bat mode from Vampirism
By leaving bat mode and reenabling the mod I was able to rejoin with my skin of choice, but it appears that leaving the world while in bat mode causes this mod to break down.

**Comment by ThisIsAVeryOriginalName** [comment]
Further testing and it doesnt replicate... go figure

**Comment by ThisIsAVeryOriginalName** [comment]
I isolated this mod into its own seperate modpack for 1.19.2, and it is still throwing the error, meaning its not correlated to any other mods, so I guess the 1.19.2 version just isn't working

**Comment by edoren** [comment]
Can you please add more information of the issue by filling this:


**Describe the bug**
A clear and concise description of what the bug is.

**Mod Loader**
 - [ ] Forge
 - [ ] NeoForge
 - [ ] Fabric

**Version Info (Please complete the following information)**
 - Mod Loader: [e.g. 51.0.22]
 - SkinChanger Version: [e.g. 0.6.1]
 - Minecraft Version: [e.g. 1.21.0]

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Logs**
Add logs to help explain your problem. You can find them inside the logs folder of your Minecraft instance.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by edoren** [comment]
Found the issue, [this ](https://github.com/edoren/SkinChanger/commit/cc9c45e89e8c5d4afff5418676a0bc0d594c20cb) should fix it for 1.19 and further. Please reopen if it happens again.
