### ISSUE TITLE
Ładowanie skórek (Loading skins)

### ISSUE THREAD

**Issue by Omi-omo** [edoren/SkinChanger#33]
Dzień dobry mam pytanie od początku gdy mod był działał on dobrze i ładował wszystkie skórki ale do czasu bo ostatnio już nie ładuje żadnej skórki pokazuje błąd i nie wiem jak go naprawić próbowałem go odinstalować i znów zainstalować i nie działa jak powinien, jest on na serwerze aternos wersja Minecrafta to 1.20.1 proszę o pomoc bo mamy wielki plan na serwerze dziękuję.

Translated:
Good morning, I have a question from the beginning, when the mod was installed, it worked well and loaded all the skins, but recently it doesn't load any skins anymore, it shows an error and I don't know how to fix it, I tried to uninstall and reinstall it and it doesn't work as it should, it's on the server aternos Minecraft version is 1.20.1 please help because we have a big plan on the server thank you.

**Comment by Omi-omo** [comment]
Nie działa wogule próbowałem wszystkiego skórki jak nadal nie ładują się co zrobić???

**Comment by edoren** [comment]
Hello, please fill this information with more details, also please use English to facilitate communication:

**Describe the bug**
A clear and concise description of what the bug is.

**Mod Loader**
 - [ ] Forge
 - [ ] NeoForge
 - [ ] Fabric

**Version Info (Please complete the following information)**
 - Mod Loader: [e.g. 51.0.22]
 - SkinChanger Version: [e.g. 0.6.1]
 - Minecraft Version: [e.g. 1.21.0]

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Logs**
Add logs to help explain your problem. You can find them inside the logs folder of your Minecraft instance.

**Screenshots**
If applicable, add screenshots to help explain your problem.
