### ISSUE TITLE
Skinchanger mod bug

### ISSUE THREAD

**Issue by JxstMasa** [edoren/SkinChanger#39]
Minecraft version 1.20.1
It said in the chat "skin successfully loaded" bit it didnt load.
Skin is over Url

**Comment by PatoMarr3qu1sta** [comment]
Same problem...

**Comment by salk2k** [comment]
> Minecraft version 1.20.1 It said in the chat "skin successfully loaded" bit it didnt load. Skin is over Url

me too

**Comment by edoren** [comment]
Hello, please fill this information to have more context of the bug:

**Describe the bug**
A clear and concise description of what the bug is.

**Mod Loader**
 - [ ] Forge
 - [ ] NeoForge
 - [ ] Fabric

**Version Info (Please complete the following information)**
 - Mod Loader: [e.g. 51.0.22]
 - SkinChanger Version: [e.g. 0.6.1]
 - Minecraft Version: [e.g. 1.21.0]

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Logs**
Add logs to help explain your problem. You can find them inside the logs folder of your Minecraft instance.

**Screenshots**
If applicable, add screenshots to help explain your problem.
